######################################################################
# Automatically generated by qmake (3.0) Mon Dec 5 09:09:06 2016
######################################################################

TEMPLATE = app
TARGET = ras
INCLUDEPATH += .


# Additional part for DADM 
QT+=widgets
CONFIG += c++11


# Input
HEADERS += circlewidget.h getdata.h getSocket.h window.h
SOURCES += circlewidget.cpp getdata.cpp main.cpp window.cpp
RESOURCES += picture/res.qrc
